requires 'namespace::autoclean';
requires 'Cpanel::JSON::XS';
requires 'Plack';
requires 'Moose';
requires 'Mojolicious';
requires 'Mojo::Pg';
requires 'DBIx::Class';
requires 'DBD::Pg';
requires 'DateTime';
